# -*- encoding: utf-8 -*-

=begin
#Platform API

#Melio Platform API enables partners to perform partner-related operations in Melio's system, for themselves, and on behalf of their system's users.

The version of the OpenAPI document: 1.0
Contact: platform@melio.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

$:.push File.expand_path("../lib", __FILE__)
require "melio-platform-api-client/version"

Gem::Specification.new do |s|
  s.name        = "melio-platform-api-client"
  s.version     = MelioPlatformApiClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Melio"]
  s.email       = ["platform@melio.com"]
  s.homepage    = "https://docs.melio.com"
  s.summary     = "Platform API Ruby Gem"
  s.description = "Melio Platform API enables partners to perform partner-related operations in Melio&#39;s system"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
