=begin
#Platform API

#Melio Platform API enables partners to perform partner-related operations in Melio's system, for themselves, and on behalf of their system's users.

The version of the OpenAPI document: 1.0
Contact: platform@melio.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MelioPlatformApiClient::CheckoutsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CheckoutsApi' do
  before do
    # run before each test
    @api_instance = MelioPlatformApiClient::CheckoutsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CheckoutsApi' do
    it 'should create an instance of CheckoutsApi' do
      expect(@api_instance).to be_instance_of(MelioPlatformApiClient::CheckoutsApi)
    end
  end

  # unit tests for get_checkouts_checkout_id
  # Retrieve a Checkout
  # Get the status of a Checkout session
  # @param checkout_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @return [GetCheckoutsCheckoutIdResponse]
  describe 'get_checkouts_checkout_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_checkouts
  # Create a Checkout
  # Start a new Checkout session.  It is recommended to make use of all the different amount fields on the &#x60;Checkout&#x60; object: * &#x60;subtotal&#x60; - The total price of the list items, after applying item level discounts. * &#x60;grandTotal&#x60; - Equals &#x60;subtotal&#x60; minus coupons and plus taxes and shipping cost. * &#x60;outstandingBalance&#x60; - Actual amount to charge the buyer using Melio, equals &#x60;grandTotal&#x60; minus store credit used and gift certificates applied.
  # @param merchant_id 
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @option opts [PostCheckoutsRequest] :post_checkouts_request 
  # @return [PostCheckoutsResponse]
  describe 'post_checkouts test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_checkouts_checkout_id_capture
  # Capture a Checkout
  # Mark that a Checkout session is finalized by the seller and the payment can be captured
  # @param checkout_id 
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @option opts [PostCheckoutsCheckoutIdCaptureRequest] :post_checkouts_checkout_id_capture_request 
  # @return [nil]
  describe 'post_checkouts_checkout_id_capture test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_checkouts_checkout_id_complete
  # Complete a Checkout
  # Complete a Checkout session for the buyer by providing payment details
  # @param checkout_id 
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @option opts [PostCheckoutsCheckoutIdCompleteRequest] :post_checkouts_checkout_id_complete_request 
  # @return [nil]
  describe 'post_checkouts_checkout_id_complete test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
