=begin
#Platform API

#Melio Platform API enables partners to perform partner-related operations in Melio's system, for themselves, and on behalf of their system's users.

The version of the OpenAPI document: 1.0
Contact: platform@melio.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MelioPlatformApiClient::DeliveryMethodsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DeliveryMethodsApi' do
  before do
    # run before each test
    @api_instance = MelioPlatformApiClient::DeliveryMethodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeliveryMethodsApi' do
    it 'should create an instance of DeliveryMethodsApi' do
      expect(@api_instance).to be_instance_of(MelioPlatformApiClient::DeliveryMethodsApi)
    end
  end

  # unit tests for delete_delivery_methods_delivery_method_id
  # Delete a Delivery Method
  # Remove a Delivery Method from the Account
  # @param delivery_method_id 
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @return [DeletedResponse]
  describe 'delete_delivery_methods_delivery_method_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_delivery_methods
  # Retrieve all Delivery Methods
  # Retrieve a list of all Delivery Methods the Account has
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @return [GetDeliveryMethodsResponse]
  describe 'get_delivery_methods test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_delivery_methods_delivery_method_id
  # Retrieve a Delivery Method
  # Retrieve the details about a specific Delivery Method the Account has
  # @param delivery_method_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @return [GetDeliveryMethodsDeliveryMethodIdResponse]
  describe 'get_delivery_methods_delivery_method_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_vendors_vendor_id_delivery_methods
  # Retrieve a Vendor&#39;s Delivery Methods
  # Get a list of a Vendor&#39;s Delivery Methods, that can be used to sent funds to.
  # @param vendor_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @return [GetVendorsVendorIdDeliveryMethodsResponse]
  describe 'get_vendors_vendor_id_delivery_methods test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_delivery_methods
  # Create a Delivery Method
  # Add a new Delivery Method for the Account.  The &#x60;type&#x60; field determines the contents of the &#x60;details&#x60; field, according to the following mapping: * &#x60;bank-account&#x60; &#x3D;&gt; &#x60;BankAccount&#x60; * &#x60;paper-check&#x60; &#x3D;&gt; &#x60;PaperCheck&#x60; * &#x60;virtual-account&#x60; &#x3D;&gt; &#x60;VirtualAccount&#x60;
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @option opts [PostDeliveryMethodsRequest] :post_delivery_methods_request 
  # @return [PostDeliveryMethodsResponse]
  describe 'post_delivery_methods test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_vendors_vendor_id_delivery_methods
  # Create a Vendor&#39;s Delivery Method
  # @param vendor_id 
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @option opts [PostDeliveryMethodsRequest] :body 
  # @return [PostVendorsVendorIdDeliveryMethodsResponse]
  describe 'post_vendors_vendor_id_delivery_methods test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
