=begin
#Platform API

#Melio Platform API enables partners to perform partner-related operations in Melio's system, for themselves, and on behalf of their system's users.

The version of the OpenAPI document: 1.0
Contact: platform@melio.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MelioPlatformApiClient::FinancingApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FinancingApi' do
  before do
    # run before each test
    @api_instance = MelioPlatformApiClient::FinancingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FinancingApi' do
    it 'should create an instance of FinancingApi' do
      expect(@api_instance).to be_instance_of(MelioPlatformApiClient::FinancingApi)
    end
  end

  # unit tests for get_financing_status
  # Retrieve an Account&#39;s financing status
  # Return the current status and balance of an account&#39;s financing qualification. The account may be in one of a few steps, defined by the response&#39;s &#x60;status&#x60; enum: - Undetermined (&#x60;undetermined&#x60; status): The account hasn&#39;t qualified yet, or the qualification has expired - Pending (&#x60;pending&#x60; status): The account has requested qualification, and awaiting for response. - Ineligible (&#x60;ineligible&#x60; status): The account is currently not eligible for financing. - Eligible (&#x60;eligible&#x60; status): The account is eligibile for financing. In this case, the additional &#x60;balance&#x60; field would be populated with the remaining credit balance.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @return [GetFinancingResponse]
  describe 'get_financing_status test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_financing
  # Apply for financing for an Account
  # Accounts that wish to use financing must qualify for it. Call this method with values collected based on the result of &#x60;GET /financing&#x60;  This operation may take a long time (30 seconds).
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @option opts [PostFinancingRequest] :post_financing_request 
  # @return [PostFinancingResponse]
  describe 'post_financing test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_financing_transaction
  # Request Transactional Financing
  # An eligible Account must request transactional approval for each financed transaction they intend to perform. The result of this operation returns a token that should be used when completing other payments through Melio.  This operation may take a long time (10 seconds).
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @option opts [PostFinancingTransactionalRequest] :post_financing_transactional_request 
  # @return [PostFinancingTransactionalResponse]
  describe 'post_financing_transaction test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
