=begin
#Platform API

#Melio Platform API enables partners to perform partner-related operations in Melio's system, for themselves, and on behalf of their system's users.

The version of the OpenAPI document: 1.0
Contact: platform@melio.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MelioPlatformApiClient::FundingSourcesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'FundingSourcesApi' do
  before do
    # run before each test
    @api_instance = MelioPlatformApiClient::FundingSourcesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of FundingSourcesApi' do
    it 'should create an instance of FundingSourcesApi' do
      expect(@api_instance).to be_instance_of(MelioPlatformApiClient::FundingSourcesApi)
    end
  end

  # unit tests for delete_funding_sources_funding_source_id
  # Delete a Funding Source
  # Remove a Funding Source from the Account
  # @param funding_source_id 
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @return [DeletedResponse]
  describe 'delete_funding_sources_funding_source_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_funding_sources
  # Get all Funding Sources
  # Retrieve the Funding Sources of an Account
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @return [GetFundingSourcesResponse]
  describe 'get_funding_sources test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_funding_sources_funding_source_id
  # Retrieve a Funding Source
  # Retrieve details about a specific Funding Source
  # @param funding_source_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @return [GetFundingSourcesFundingSourceIdResponse]
  describe 'get_funding_sources_funding_source_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_funding_sources
  # Create a Funding Source
  # Create a new Funding Source for the Account.  The &#x60;type&#x60; field determines the contents of the &#x60;details&#x60; field, according to the following mapping: * &#x60;bank-account&#x60; &#x3D;&gt; &#x60;BankAccount&#x60; * &#x60;plaid&#x60; &#x3D;&gt; &#x60;PlaidDetails&#x60; * &#x60;card&#x60; &#x3D;&gt; &#x60;Card&#x60;
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @option opts [PostFundingSourcesRequest] :post_funding_sources_request 
  # @return [PostFundingSourcesResponse]
  describe 'post_funding_sources test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
