=begin
#Platform API

#Melio Platform API enables partners to perform partner-related operations in Melio's system, for themselves, and on behalf of their system's users.

The version of the OpenAPI document: 1.0
Contact: platform@melio.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MelioPlatformApiClient::PaymentIntentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PaymentIntentsApi' do
  before do
    # run before each test
    @api_instance = MelioPlatformApiClient::PaymentIntentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PaymentIntentsApi' do
    it 'should create an instance of PaymentIntentsApi' do
      expect(@api_instance).to be_instance_of(MelioPlatformApiClient::PaymentIntentsApi)
    end
  end

  # unit tests for get_payment_intents
  # Retrieve all Payment Intents
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @return [GetPaymentIntentsResponse]
  describe 'get_payment_intents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_payment_intents_payment_intent_id
  # Retrieve a Payment Intent
  # @param payment_intent_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @return [GetPaymentIntentsPaymentIntentIdResponse]
  describe 'get_payment_intents_payment_intent_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_payment_intents_payment_intent_id
  # Update a Payment Intent
  # Update an existing Payment Intent.  The request&#39;s body can be partial, and only provided fields will be overwritten. Set a field to &#x60;null&#x60; in order to remove its contents.
  # @param payment_intent_id 
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @option opts [PatchPaymentIntentsPaymentIntentIdRequest] :patch_payment_intents_payment_intent_id_request 
  # @return [PatchPaymentIntentsPaymentIntentIdResponse]
  describe 'patch_payment_intents_payment_intent_id test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_payment_intents
  # Create a Payment Intent
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @option opts [PostPaymentIntentsRequest] :post_payment_intents_request 
  # @return [PostPaymentIntentsResponse]
  describe 'post_payment_intents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_payment_intents_bulk
  # Create multiple Payment Intents
  # Create multiple Payment Intents based on a provided list.
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @option opts [PostPaymentIntentsBulkRequest] :post_payment_intents_bulk_request 
  # @return [PostPaymentIntentsBulkResponse]
  describe 'post_payment_intents_bulk test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_payment_intents_payment_intent_id_confirm
  # Confirm a Payment Intent
  # Confirm this Payment Intent and produce a Payment based on the current configuration.
  # @param payment_intent_id 
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @return [PostPaymentIntentsPaymentIntentIdPaymentResponse]
  describe 'post_payment_intents_payment_intent_id_confirm test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
