=begin
#Platform API

#Melio Platform API enables partners to perform partner-related operations in Melio's system, for themselves, and on behalf of their system's users.

The version of the OpenAPI document: 1.0
Contact: platform@melio.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for MelioPlatformApiClient::VendorDirectoryApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'VendorDirectoryApi' do
  before do
    # run before each test
    @api_instance = MelioPlatformApiClient::VendorDirectoryApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VendorDirectoryApi' do
    it 'should create an instance of VendorDirectoryApi' do
      expect(@api_instance).to be_instance_of(MelioPlatformApiClient::VendorDirectoryApi)
    end
  end

  # unit tests for get_vendor_directory
  # Retrieve all filtered Vendors in the Vendor Directory
  # List of all Vendors in the Vendor Directory, filtered by the name parameter and with provided query limit (default 20).
  # @param name The name of the Vendor to query
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :limit The number of items to include in the returned list
  # @return [GetVendorDirectoryResponse]
  describe 'get_vendor_directory test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for post_vendors_from_vendor_directory
  # Create a Vendor from Vendor Directory
  # Add a specific Vendor from Vendor Directory by its ID to an Account, and clone its Delivery Method in case of biller account.
  # @param idempotency_key Unique idempotency key
  # @param [Hash] opts the optional parameters
  # @option opts [String] :melio_account The &#x60;Melio-Account&#x60; header is used when a Partner wants to perform an operation on behalf of one of its Accounts. It contains the Account&#39;s ID which returned when creating the Account, or when retrieving all of the Partner&#39;s Accounts. Note that most operations are not permitted without the presence of this header.
  # @option opts [PostVendorsFromVendorDirectoryRequest] :post_vendors_from_vendor_directory_request 
  # @return [PostVendorsFromVendorDirectoryResponse]
  describe 'post_vendors_from_vendor_directory test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
