=begin
#Platform API

#Melio Platform API enables partners to perform partner-related operations in Melio's system, for themselves, and on behalf of their system's users.

The version of the OpenAPI document: 1.0
Contact: platform@melio.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for MelioPlatformApiClient::GetFilesFileIdDataResponseDataVendorInfo
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe MelioPlatformApiClient::GetFilesFileIdDataResponseDataVendorInfo do
  let(:instance) { MelioPlatformApiClient::GetFilesFileIdDataResponseDataVendorInfo.new }

  describe 'test an instance of GetFilesFileIdDataResponseDataVendorInfo' do
    it 'should create an instance of GetFilesFileIdDataResponseDataVendorInfo' do
      expect(instance).to be_instance_of(MelioPlatformApiClient::GetFilesFileIdDataResponseDataVendorInfo)
    end
  end
  describe 'test attribute "name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "matched_name"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
